Yeni java egzersizleri 3
yncrahmet/backend pull request #8
Opened 2024-03-04 09:58 UTC by yncrahmet

2024-03-04 13:49 UTC, JamshidS requested changes

2024-03-04 13:49 UTC, JamshidS commented on Java Exercises/Java Exercises.iml
> +<?xml version="1.0" encoding="UTF-8"?>
bu dosyalar ne?

2024-03-04 13:49 UTC, JamshidS commented on banka/banka.iml
> +  <component name="NewModuleRootManager" inherit-compiler-output="true">
bunlari gondermene gerek yok ayrica iki tane olusturup gondermisin

2024-03-04 13:52 UTC, yncrahmet commented
İki kere olduğunu bilemedim diğer dosyalar proje içimdeydi hocam. Direk proje klasörünü attım

2024-03-05 14:48 UTC, JamshidS approved these changes

2024-03-05 14:49 UTC, merged